pocetna:
    path:     /
    defaults: { _controller: BGPGlagoljicaBundle:Pocetna:index }

konvertor:
    path:     /konvertor
    defaults: { _controller: BGPGlagoljicaBundle:Konvertor:index }

onama:
    path:     /onama
    defaults: { _controller: BGPGlagoljicaBundle:Onama:index }

glagoljica:
    path:     /glagoljica
    defaults: { _controller: BGPGlagoljicaBundle:Glagoljica:index }

dajIzlazeZaUlaz:
    path:     /dajIzlazeZaUlaz/{ulaz}
    defaults: { _controller: BGPGlagoljicaBundle:DajIzlazeZaUlaz:index }

konverzija:
    path:     /konverzija
    defaults: { _controller: BGPGlagoljicaBundle:Konverzija:index }
    methods:  [POST]